### PR TITLE
Upgrade go version to 1.14.1

### PR DESCRIPTION
**Pull request by kakkoyun**

### CODE REVIEW

**Comment by kakkoyun** [comment]
As far as I know, it's fixed and there's a new minor version https://golang.org/doc/devel/release.html#go1.14

**Comment by squat** [comment]
I think in general we should be pinning to exact go versions specifically to avoid issues like building with the wrong go image because go1.14 is .0 in some places and .1 in others. How about pinning this to go1.14.1?

**Comment by kakkoyun** [comment]
@squat Makes sense. I've pinned it.

**Comment by squat** [comment]
:+1:

**Pull request merged**
