### PR TITLE
jsonnet,examples: add RBAC + tenants to manifests

### PR DESCRIPTION
**Pull request by squat**
This PR adds RBAC and tenants configuration files to the generated
manifests by extending the jsonnet library for the API.

cc @metalmatze @periklis

### CODE REVIEW

**Comment by squat** [comment]
That's true, I actually started with `withTenants` and `withRBAC`, but I saw that we use this other pattern, e.g. : https://github.com/observatorium/configuration/blob/master/components/up.libsonnet#L93

I'm very happy to move it to `with...` if you two like it more

**Comment by periklis** [comment]
I am not the jsonnet pro here. I'll pass to @metalmatze . The `with...` approach gives me the impression that it works best when amending with new or overwrite named fields. It maybe be akward replacing in arrays though.

**Comment by metalmatze** [comment]
It's a tradeoff for sure right now and we're still experimenting.
The problem with all the `withFoo` functions is that it scatters the configuration across multiple different functions / objects in the file. It's super hard to grasp at a certain point.
We've seen that happening in our downstream / internal repository that uses https://github.com/observatorium/configuration/. 
For the API I'm actually fine with the approach in this PR right now.

**Comment by squat** [comment]
cool, then I'm happy with going this way for now too

**Comment by periklis** [comment]
@metalmatze you have a point here, scattering configuration is hard for maintenance. I kept the `withFoo` approach in my loki configuration code for the sort like service monitors that introduction optional resources.

**Pull request merged**
