### PR TITLE
Add redoc for OpenAPI spec based documentation

### PR DESCRIPTION
**Pull request by saswatamcode**
This PR adds an API documentation page for Observatorium using [redocly](https://redocly.com/).

### CODE REVIEW

**Comment by saswatamcode** [comment]
Deploy preview: https://deploy-preview-483--observatorium.netlify.app/docs/api

**Review by douglascamata — APPROVED** [review]
Looks neat!

**Comment by douglascamata** [comment]
@saswatamcode don't know if you noticed, but there is a failed check for docs formatting/linting.

**Comment by saswatamcode** [comment]
Yeah, seems like slack.cncf.io is having some problems...nothing changed on the markdown side. :)

**Comment by jessicalins** [comment]
Looks nice! <3 
would it be possible to add an override to the docs to drop the `v1` suffix? I think without it is nicer to read.
Not necessarily changing the [spec](https://raw.githubusercontent.com/observatorium/api/main/client/spec.yaml), but only in the docs

**Comment by saswatamcode** [comment]
Yeah, I'm trying to see what can be customized with this!

**Comment by saswatamcode** [comment]
Let's change the spec later on, with some suitable tags/versions later on. For now, just adding a logo in the spec itself here: https://github.com/observatorium/api/pull/314

Once merged, this PR would be ready to go! 🙂

**Review by jessicalins — APPROVED** [review]
great work! :memo: 
@saswatamcode lets then add an issue to update the spec later on

**Pull request merged**
