### PR TITLE
jsonnet: Update gubernator rate limiting component to latest

### PR DESCRIPTION
**Pull request by PhilipGough**

### CODE REVIEW

**Review by squat — APPROVED** [review]
Lgtm, I think netlify had a hiccough

**Comment by PhilipGough** [comment]
@squat yeah it seems to be having issues but some circle CI failures too so will investigate!

**Comment by saswatamcode** [comment]
Seems like the Netlify build images have been deprecated, and need to updated in the Observatorium team account.

**Comment by squat** [comment]
> Seems like the Netlify build images have been deprecated, and need to updated in the Observatorium team account.

who has access to the Netlify team account so we can update the build image?

**Comment by matej-g** [comment]
> who has access to the Netlify team account so we can update the build image?

Hm I'm afraid it might be only @bwplotka who's on a break 😞

**Review by saswatamcode — APPROVED** [review]
Thanks!

**Pull request merged**
