### PR TITLE
Cleaned docs + added obsctl to bingo.

### PR DESCRIPTION
**Pull request by bwplotka**
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Review by PhilipGough — APPROVED** [review]
lgtm

**Review by moadz — APPROVED** [review]
LGTM

**Review by kakkoyun — APPROVED** [review]
:rocket:

**Comment by squat** [comment]
Looks good. We don't actually use obsctl for anything in this repo, right?

**Comment by bwplotka** [comment]
@squat just noticed your comment! We use it for testing deployment, interactively locally, and this is what we recommend, so I thought it would be easier if the main repo has it. Otherwise, our CI does not. We are trying to improve usability for new users.. but your question is solid then, I should remove it. 🙃  Let's me know if your opinion is strong here but I violated YAGNI here, agree - my bad.

**Pull request merged**
