### PR TITLE
Update Gubernator and run unpriviledged

### PR DESCRIPTION
**Pull request by metalmatze**
Mostly to run Gubernator on ports > 1024.

### CODE REVIEW

**Review by kakkoyun — APPROVED** [review]
Perfect 💯

**Comment by kakkoyun** [comment]
The logs read/write tests are broken because of OPA port clash AFAIT.

**Comment by metalmatze** [comment]
```{"err":"listen tcp :8181: bind: address already in use","level":"fatal","msg":"Listener failed.","time":"2020-12-04T11:39:40Z"}
```
I need to find out what uses that port already and change Gubernator to a different one, I think.

**Comment by squat** [comment]
that's right, the OPA http server is running on 8181: https://github.com/observatorium/observatorium/blob/master/test/config/tenants.yaml#L28

**Review by kakkoyun — APPROVED** [review]

**Pull request merged**
