### PR TITLE
TLS enabled healthchecks

### PR DESCRIPTION
**Pull request by nmagnezi**

### CODE REVIEW

**Comment by nmagnezi** [comment]
this is based on top of [PR-67](https://github.com/observatorium/observatorium/pull/67), which should be merged first.

**Comment by nmagnezi** [comment]
@metalmatze

**Comment by nmagnezi** [comment]
Ready for review.
CC: @metalmatze @squat

**Comment by squat** [comment]
hey @nmagnezi this mostly just needs a rebase to account for the new flags
Also, note that for the mTLS option, you'll need to specify a server CA file and a client cert + key for the healthchecks, as we do here https://github.com/observatorium/observatorium/blob/master/test/integration.sh#L36-L38

**Comment by nmagnezi** [comment]
> hey @nmagnezi this mostly just needs a rebase to account for the new flags
> Also, note that for the mTLS option, you'll need to specify a server CA file and a client cert + key for the healthchecks, as we do here https://github.com/observatorium/observatorium/blob/master/test/integration.sh#L36-L38

Rebase done 😃

**Comment by nmagnezi** [comment]
> hey @nmagnezi this mostly just needs a rebase to account for the new flags
> Also, note that for the mTLS option, you'll need to specify a server CA file and a client cert + key for the healthchecks, as we do here https://github.com/observatorium/observatorium/blob/master/test/integration.sh#L36-L38

I've added the new TLS flags mentioned in `integration.sh`

**Pull request merged**
