### PR TITLE
Implement ability to disable endpoints

### LINKED ISSUE #6: Add a Dead man's switch for remote write handler
TBD

Return 4XX to mitigate certain incidents

cc @metalmatze

### PR DESCRIPTION
**Pull request by kakkoyun**
This PR attempts fix #6.

cc @squat @metalmatze @brancz 

Adds two new flags
```console
  -metrics.read.disable
    	The flag to disable handling read requests.
  -metrics.write.disable
    	The flag to disable handling write requests.
```

### CODE REVIEW

**Comment by squat** [comment]
cool :)

**Comment by brancz** [comment]
I would expect that this is rather a per tenant configuration instead of all or nothing.

**Comment by kakkoyun** [comment]
@brancz @squat Should I update this one? Or should we defer this until we have per-tenant configuration?

**Comment by kakkoyun** [comment]
Closing this one. This needs reconsideration after implementing a tenant mechanism.

**Pull request closed without merging**
