### PR TITLE
Rules API proposal: Accommodate alerting rules

### PR DESCRIPTION
**Pull request by jessicalins**
This PR updates the Rules API proposal to also accommodate alerting rules. I just reword the proposal and removed the "What if a user gives us an alerting rule" section.

### CODE REVIEW

**Review by squat — APPROVED** [review]
I love it

**Comment by jessicalins** [comment]
@squat I don't really get why tests are failing :( (apparently something in `build.command` from `netfly.toml`? (from the [logs](https://app.netlify.com/sites/observatorium/deploys/618023c18f7386000725c2a0))

**Comment by squat** [comment]
@jessicalins the build is failing because the Makefile target `web` requires the dependency `$(WEBSITE_DIR)/node_modules` however this dependency was removed in this PR (https://github.com/observatorium/observatorium/pull/422/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L37) so `make` complains that it cannot satisfy the dependency.

**Comment by saswatamcode** [comment]
I kept the `$(WEBSITE_DIR)/node_modules` pre-requisite so that `web` or `web-serve` cannot execute fully if `website/node_modules` isn't present. The `web-pre` target creates this directory by executing `npm i` inside of `website/themes/doks` and is a pre-requisite for `web` & `web-serve`. 

It seems like this was a pre-requisite ordering issue. But then it should have come up earlier? 
A reason why it didn't occur earlier might be due to Netlify caching files between builds, so the `website/node_modules` target would be satisfied by that so earlier PRs didn't have this issue. 🤔

According to [docs](https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html), it can be solved by changing the `web` & `web-serve` targets to have order-only prerequisites.
I'll raise a PR for this. 🙂

**Comment by saswatamcode** [comment]
@jessicalins Rebasing should now fix the build! 🙂

**Comment by ianbillett** [comment]
Thank you @saswatamcode :raised_hands:

**Review by ianbillett — DISMISSED** [review]

**Pull request merged**
