### PR TITLE
add imagepullpolicy support.

### PR DESCRIPTION
**Pull request by morvencao**
ref: observatorium/operator#76
Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by saswatamcode** [comment]
Thanks for this! Can you run `make generate` once so that the jsonnet changes are reflected in `configuration/`? Build fails due to this. 🙂

**Comment by morvencao** [comment]
thanks @saswatamcode Done.

**Comment by squat** [comment]
The e2e tests are failing because it seems that kube-prometheus renamed a file in main. We should pin the version of the file we are downloading so that we are not so fragile.
```
Thanks for using kind! 😊
error: unable to read URL "https://raw.githubusercontent.com/coreos/kube-prometheus/master/manifests/setup/prometheus-operator-0servicemonitorCustomResourceDefinition.yaml", server reported 404 Not Found, status code=404
```
The new file is located at: https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/setup/0servicemonitorCustomResourceDefinition.yaml

**Comment by morvencao** [comment]
I found @saswatamcode raised another PR to fix the failing e2e testing, see: https://github.com/observatorium/observatorium/pull/447

**Comment by saswatamcode** [comment]
Have closed #447 in favor of #448. 🙂

**Comment by morvencao** [comment]
Rebased the code changes to pass the e2e tests.

**Comment by morvencao** [comment]
@saswatamcode @squat PTAL

**Review by saswatamcode — APPROVED** [review]
Thanks! LGTM

**Comment by squat** [comment]
@morvencao this PR seems to only add the field for a small subset of all of the components. Are these the only ones you are interested in? Or perhaps the only ones that don't expose this option?

**Comment by morvencao** [comment]
thanks @squat 
Just updated `minio` for the imagepullpolicy, for thanos resources, they don't have exposed this option yet.

**Comment by morvencao** [comment]
@squat ^^

**Review by clyang82 — APPROVED** [review]

**Review by bwplotka — APPROVED** [review]
Thanks!

**Pull request merged**
