### PR TITLE
allow serverName empty

### PR DESCRIPTION
**Pull request by clyang82**

### CODE REVIEW

**Comment by periklis** [comment]
@clyang82 Do the healthcheck work under TLS w/o server name defined?

**Comment by clyang82** [comment]
> @clyang82 Does the healthcheck work under TLS w/o server name defined?

This does not work in most production environment. but it works in test environment.

**Review by squat — APPROVED** [review]

**Comment by squat** [comment]
> Does the healthcheck work under TLS w/o server name defined?

Yes it does but then you need to have `localhost` as one of the SANs in the cert

**Pull request merged**
