### PR TITLE
Migrate to Go jsonnet formatter

### PR DESCRIPTION
**Pull request by kakkoyun**
# Changes

* Relevant changes https://github.com/observatorium/observatorium/commit/3be30b0c2505533c9db059f0d1f1fd9d53d23fa1
* Vendor

cc @metalmatze @brancz

### CODE REVIEW

**Comment by squat** [comment]
Awesome that we can finally do this!

**Comment by krasi-georgiev** [comment]
had a quick look, and  I don't think there is a  CI target that checks the jsonnet is properly formatted.

**Comment by squat** [comment]
That's true, the lint target depends on `go-fmt` but not `jsonnet-fmt`

**Comment by kakkoyun** [comment]
@krasi-georgiev Thanks for pointing out, I'll send a fix.

**Pull request merged**
